// Survey definition — The Great Indian Monsoon Survey v2
// Every question maps to a pitch-deck hypothesis (see monsoon-survey-v2.md).
// Types: single (tap to advance), multi (checkboxes + continue), textarea.

const SURVEY_QUESTIONS = [
  {
    id: "state",
    section: "The basics",
    type: "single",
    layout: "grid",
    required: true,
    title: "Which state do you live in?",
    otherOption: "Other state",
    options: [
      "Kerala",
      "Maharashtra",
      "Goa",
      "Karnataka",
      "Tamil Nadu",
      "West Bengal",
      "Assam / North-East",
      "Odisha",
      "Telangana / Andhra Pradesh",
      "Gujarat",
      "Other state",
    ],
  },
  {
    id: "commute",
    section: "The basics",
    type: "single",
    required: true,
    title: "During the rainy season, how do you mostly get around on a normal day?",
    options: [
      "Two-wheeler (scooter / bike)",
      "Bus / metro / auto + walking",
      "Car or cab",
      "I rarely need to go out",
    ],
  },
  {
    id: "occupation",
    section: "The basics",
    type: "single",
    required: true,
    title: "What best describes you?",
    options: [
      "Student",
      "Office-going professional",
      "Work from home / hybrid",
      "Field work (sales, delivery, site visits)",
      "Business owner / self-employed",
      "Homemaker / other",
    ],
  },
  {
    id: "gear_owned",
    section: "What you do today",
    type: "multi",
    required: true,
    minSelect: 1,
    title: "What rain gear do you own right now?",
    hint: "Tick everything that applies.",
    options: [
      "Umbrella",
      "Plastic poncho / cheap raincoat (under ₹500)",
      "Two-wheeler rain suit (Duckback, Zeel, Wildcraft type)",
      "Sports-brand rain jacket (Decathlon etc.)",
      "Premium / imported jacket (Columbia, North Face etc.)",
      "Nothing — I manage / get wet",
    ],
  },
  {
    id: "last_purchase",
    section: "What you do today",
    type: "single",
    required: true,
    title: "When did you last spend money on rain gear?",
    options: [
      "Within the past year",
      "1–3 years ago",
      "More than 3 years ago",
      "Never",
    ],
  },
  {
    id: "last_cost",
    section: "What you do today",
    type: "single",
    required: true,
    title: "Roughly how much did it cost?",
    options: [
      "Under ₹300",
      "₹300–800",
      "₹800–1,500",
      "₹1,500–3,000",
      "More than ₹3,000",
      "Never bought any",
    ],
  },
  {
    id: "durability",
    section: "What you do today",
    type: "single",
    required: false,
    title: "How many monsoons did your last raincoat / rain suit actually survive?",
    options: [
      "Didn't even survive one",
      "One or two",
      "Three or more",
      "Still going strong",
      "Don't own one",
    ],
  },
  {
    id: "rain_story",
    section: "What you do today",
    type: "textarea",
    required: true,
    title:
      "Think of the last time heavy rain caught you when you HAD to be somewhere. What did you do, and what annoyed you most?",
    hint: "Two or three honest lines. This is the most useful answer in the whole survey.",
    placeholder: "It was pouring and I had to reach…",
  },
  {
    id: "searched",
    section: "What you do today",
    type: "single",
    required: true,
    title:
      "In the past year, did you actively go looking for better rain gear — online or in a store?",
    options: [
      "Yes — and I bought something",
      "Yes — but nothing was worth buying",
      "No — what I have works fine",
      "No — never crossed my mind",
    ],
  },
  {
    id: "phone_habit",
    section: "Two quick details",
    type: "single",
    required: false,
    title: "When you're out in the rain, where does your phone go?",
    options: [
      "Pocket — fingers crossed",
      "Plastic bag / pouch",
      "Inside my bag / under the seat — basically unreachable",
      "A waterproof pocket in my gear",
      "I just don't take it out",
    ],
  },
  {
    id: "arrival",
    section: "Two quick details",
    type: "single",
    required: false,
    title:
      "When you arrive somewhere — office, college, a café — what happens to your rain gear?",
    options: [
      "Stuffed into a bag — wet mess and all",
      "Left on the bike / outside",
      "Hung up somewhere, no problem",
      "Honestly, it's a bit embarrassing — I get rid of it fast",
      "Doesn't apply to me",
    ],
  },
  {
    id: "rider_failure",
    section: "For riders",
    type: "single",
    required: false,
    title: "When you ride in rain, what fails FIRST with your current gear?",
    showIf: (answers) => answers.commute === "Two-wheeler (scooter / bike)",
    options: [
      "Water gets in anyway (neck, wrists, seams)",
      "Legs / thighs get soaked",
      "It's a sauna inside — I arrive sweaty instead of wet",
      "Helmet / hood / visibility problems",
      "It tears or breaks",
      "It looks terrible when I arrive",
      "Nothing — it works fine",
    ],
  },
  {
    id: "top_two",
    section: "What would win you over",
    type: "multi",
    required: true,
    exactSelect: 2,
    title:
      "If a genuinely better rain jacket existed, which TWO things would matter most to you?",
    hint: "Pick exactly two. Choosing is the whole point.",
    options: [
      "Completely dry in a proper downpour",
      "Doesn't turn into a sauna in Indian heat",
      "Looks good enough to wear even when it's not raining",
      "Packs small and light enough to carry every day",
      "Made for two-wheelers (length, helmet fit, night visibility)",
      "Lasts three or more monsoons",
    ],
  },
  {
    id: "max_price",
    section: "What would win you over",
    type: "single",
    required: true,
    title:
      "What's the most you'd realistically pay for rain gear that nails your top two?",
    options: [
      "Under ₹500",
      "₹500–1,500",
      "₹1,500–3,000",
      "₹3,000–5,000",
      "Above ₹5,000",
    ],
  },
  {
    id: "price_ceiling",
    section: "What would win you over",
    type: "single",
    required: false,
    title:
      "And honestly — at what price would you not even consider it, no matter how good?",
    options: [
      "Above ₹1,000",
      "Above ₹2,000",
      "Above ₹3,500",
      "Above ₹5,000",
      "Price isn't really the issue for me",
    ],
  },
  {
    id: "channel",
    section: "What would win you over",
    type: "single",
    required: false,
    title: "If you decided to buy, where would you most likely buy it?",
    options: [
      "Amazon / Flipkart",
      "The brand's own website",
      "Myntra / Ajio / Nykaa",
      "Decathlon or a gear store",
      "A local shop I can walk into",
    ],
  },
  {
    id: "age",
    section: "About you",
    type: "single",
    required: false,
    title: "Your age?",
    options: ["Under 20", "20–28", "29–35", "36–45", "46+"],
  },
  {
    id: "gender",
    section: "About you",
    type: "single",
    required: false,
    title: "Gender?",
    options: ["Woman", "Man", "Prefer not to say"],
  },
];
